name: locusfocusR
channels:
  - bioconda
  - r
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - _r-mutex=1.0.1=anacondar_1
  - alabaster=0.7.12=py37_0
  - argh=0.26.2=py37_0
  - astroid=2.3.3=py37_0
  - atomicwrites=1.4.0=py_0
  - attrs=19.3.0=py_0
  - autopep8=1.5.3=py_0
  - babel=2.8.0=py_0
  - backcall=0.2.0=py_0
  - beautifulsoup4=4.9.1=py37_0
  - binutils_impl_linux-64=2.34=h53a641e_7
  - binutils_linux-64=2.34=hc952b39_20
  - blas=2.17=openblas
  - bleach=3.1.5=py_0
  - bokeh=2.1.1=py37_0
  - brotlipy=0.7.0=py37h7b6447c_1000
  - bs4=4.9.1=0
  - bwidget=1.9.14=0
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2020.6.24=0
  - cairo=1.16.0=hcf35c78_1003
  - certifi=2020.6.20=py37_0
  - cffi=1.14.0=py37h2e261b9_0
  - chardet=3.0.4=py37_1003
  - click=7.1.2=py_0
  - cloudpickle=1.5.0=py_0
  - cryptography=2.9.2=py37h1ba5d50_0
  - curl=7.71.1=he644dc0_1
  - cycler=0.10.0=py37_0
  - cytoolz=0.10.1=py37h7b6447c_0
  - dask=2.20.0=py_0
  - dask-core=2.20.0=py_0
  - dbus=1.13.16=hb2f20db_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - diff-match-patch=20181111=py_0
  - distributed=2.20.0=py37_0
  - docutils=0.16=py37_1
  - entrypoints=0.3=py37_0
  - expat=2.2.9=he6710b0_2
  - flake8=3.8.3=py_0
  - flask=1.1.2=py_0
  - fontconfig=2.13.1=h86ecdb6_1001
  - freetype=2.10.2=h5ab3b9f_0
  - fribidi=1.0.10=h516909a_0
  - fsspec=0.7.4=py_0
  - future=0.18.2=py37_1
  - gcc_impl_linux-64=7.5.0=hd420e75_6
  - gcc_linux-64=7.5.0=h09487f9_20
  - gettext=0.19.8.1=hd7bead4_3
  - gfortran_impl_linux-64=7.5.0=hdf63c60_6
  - gfortran_linux-64=7.5.0=h09487f9_20
  - glib=2.65.0=h6f030ca_0
  - graphite2=1.3.14=h23475e2_0
  - gsl=2.6=h294904e_0
  - gst-plugins-base=1.14.5=h0935bb2_2
  - gstreamer=1.14.5=h36ae1b5_2
  - gxx_impl_linux-64=7.5.0=hdf63c60_6
  - gxx_linux-64=7.5.0=h09487f9_20
  - harfbuzz=2.4.0=h9f30f68_3
  - heapdict=1.0.1=py_0
  - icu=64.2=he1b5a44_1
  - idna=2.10=py_0
  - imagesize=1.2.0=py_0
  - importlib-metadata=1.7.0=py37_0
  - importlib_metadata=1.7.0=0
  - intervaltree=3.0.2=py_1
  - ipykernel=5.3.2=py37h43977f1_0
  - ipython=7.16.1=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py37_0
  - isort=4.3.21=py37_0
  - itsdangerous=1.1.0=py37_0
  - jedi=0.17.1=py37_0
  - jeepney=0.4.3=py_0
  - jinja2=2.11.2=py_0
  - jpeg=9d=h516909a_0
  - jsonschema=3.2.0=py37_1
  - jupyter_client=6.1.5=py_0
  - jupyter_core=4.6.3=py37_0
  - keyring=21.2.1=py37_0
  - kiwisolver=1.2.0=py37hfd86e86_0
  - krb5=1.17.1=h173b8e3_0
  - lazy-object-proxy=1.5.0=py37h7b6447c_0
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.34=h53a641e_7
  - libblas=3.8.0=17_openblas
  - libcblas=3.8.0=17_openblas
  - libclang=9.0.1=default_hde54327_0
  - libcurl=7.71.1=hcdd3856_1
  - libdeflate=1.6=h516909a_0
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.2.0=h24d8f2e_2
  - libgfortran-ng=7.5.0=hdf63c60_6
  - libgomp=9.2.0=h24d8f2e_2
  - libiconv=1.15=h63c8f33_5
  - liblapack=3.8.0=17_openblas
  - liblapacke=3.8.0=17_openblas
  - libllvm9=9.0.1=h4a3c616_1
  - libopenblas=0.3.10=h5a2b251_0
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.18=h7b6447c_0
  - libspatialindex=1.9.3=he6710b0_0
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=9.2.0=hdf63c60_2
  - libtiff=4.1.0=h2733197_1
  - libuuid=2.32.1=h14c3975_1000
  - libxcb=1.14=h7b6447c_0
  - libxkbcommon=0.10.0=he1b5a44_0
  - libxml2=2.9.10=hee79883_0
  - llvm-openmp=10.0.0=hc9558a2_0
  - locket=0.2.0=py37_1
  - lz4-c=1.9.2=he6710b0_0
  - make=4.3=h516909a_0
  - markupsafe=1.1.1=py37h14c3975_1
  - matplotlib=3.2.2=0
  - matplotlib-base=3.2.2=py37h30547a4_0
  - mccabe=0.6.1=py37_1
  - mistune=0.8.4=py37h14c3975_1001
  - msgpack-python=1.0.0=py37hfd86e86_1
  - nbconvert=5.6.1=py37_1
  - nbformat=5.0.7=py_0
  - ncurses=6.2=he6710b0_1
  - nspr=4.26=he1b5a44_0
  - nss=3.47=he751ad9_0
  - numpy=1.18.5=py37h7130bb8_0
  - numpy-base=1.18.5=py37h2f8d375_0
  - numpydoc=1.1.0=py_0
  - olefile=0.46=py37_0
  - openssl=1.1.1g=h7b6447c_0
  - packaging=20.4=py_0
  - pandas=1.0.5=py37h0573a6f_0
  - pandoc=2.10=0
  - pandocfilters=1.4.2=py37_1
  - pango=1.42.4=h7062337_4
  - parso=0.7.0=py_0
  - partd=1.1.0=py_0
  - pathtools=0.1.2=py_1
  - pcre=8.44=he6710b0_0
  - pexpect=4.8.0=py37_1
  - pickleshare=0.7.5=py37_1001
  - pillow=7.2.0=py37hb39fc2d_0
  - pip=20.1.1=py37_1
  - pixman=0.38.0=h7b6447c_0
  - pluggy=0.13.1=py37_0
  - prompt-toolkit=3.0.5=py_0
  - psutil=5.7.0=py37h7b6447c_0
  - ptyprocess=0.6.0=py37_0
  - pycodestyle=2.6.0=py_0
  - pycparser=2.20=py_2
  - pydocstyle=5.0.2=py_0
  - pyflakes=2.2.0=py_0
  - pygments=2.6.1=py_0
  - pylint=2.4.4=py37_0
  - pymongo=3.10.1=py37h3340039_2
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=py_0
  - pyqt=5.12.3=py37h8685d9f_3
  - pyrsistent=0.16.0=py37h7b6447c_0
  - pysam=0.16.0.1=py37hc334e0b_1
  - pysocks=1.7.1=py37_1
  - python=3.7.7=hcf32534_0_cpython
  - python-dateutil=2.8.1=py_0
  - python-jsonrpc-server=0.3.4=py_1
  - python-language-server=0.34.1=py37_0
  - python_abi=3.7=1_cp37m
  - pytz=2020.1=py_0
  - pyxdg=0.26=py_0
  - pyyaml=5.3.1=py37h7b6447c_1
  - pyzmq=19.0.1=py37he6710b0_1
  - qdarkstyle=2.8.1=py_0
  - qt=5.12.5=hd8c4c69_1
  - qtawesome=0.7.2=py_0
  - qtconsole=4.7.5=py_0
  - qtpy=1.9.0=py_0
  - r-argparser=0.6=r36_1
  - r-base=3.6.3=h316533a_2
  - r-compquadform=1.4.3=r36h29659fb_0
  - r-data.table=1.12.8=r36hcdcec82_1
  - readline=8.0=h7b6447c_0
  - requests=2.24.0=py_0
  - rope=0.17.0=py_0
  - rtree=0.9.4=py37_1
  - scipy=1.5.0=py37habc2bb6_0
  - secretstorage=3.1.2=py37_1
  - sed=4.7=h1bed415_1000
  - setuptools=49.2.0=py37hc8dfbb8_0
  - six=1.15.0=py_0
  - snowballstemmer=2.0.0=py_0
  - sortedcontainers=2.2.2=py_0
  - soupsieve=2.0.1=py_0
  - sphinx=3.1.2=py_0
  - sphinxcontrib-applehelp=1.0.2=py_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=1.0.3=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.4=py_0
  - spyder=4.1.4=py37hc8dfbb8_0
  - spyder-kernels=1.9.2=py37hc8dfbb8_0
  - sqlite=3.32.3=h62c20be_0
  - tblib=1.6.0=py_0
  - testpath=0.4.4=py_0
  - tk=8.6.10=hbc83047_0
  - tktable=2.10=h14c3975_0
  - toml=0.10.1=py_0
  - toolz=0.10.0=py_0
  - tornado=6.0.4=py37h7b6447c_1
  - tqdm=4.47.0=py_0
  - traitlets=4.3.3=py37_0
  - typing_extensions=3.7.4.2=py_0
  - ujson=1.35=py37h14c3975_0
  - urllib3=1.25.9=py_0
  - watchdog=0.10.3=py37_0
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py37_1
  - werkzeug=0.16.1=py_0
  - wheel=0.34.2=py37_0
  - wrapt=1.12.1=py37h7b6447c_1
  - wurlitzer=2.0.0=py37_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.9=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - yapf=0.30.0=py_0
  - zeromq=4.3.2=he6710b0_2
  - zict=2.0.0=py_0
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.4=h0b5b093_3
  - pip:
    - blinker==1.4
    - flask-sitemap==0.3.0
    - flask-uploads==0.2.1
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
prefix: /home/naim/miniconda3/envs/locusfocusR

